#site's settings
title: oussama.sh
description: Blog's content is being loaded
url: https://oussamamater.github.io
show_downloads: false
google_analytics: UA-177143278-1
theme: jekyll-theme-hacker

#github page setting
github:
  is_project_page: false

#footer
footer: 2020 OussamaMater

#Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
